### ISSUE TITLE
Links not opening in TortoiseSVN

### ISSUE THREAD

**Issue by sheam** [masamitsu-murase/open_tortoise_svn_for_google_chrome#2]
I have installed the extension, and run copy_tsvn_tool.exe, which succeeded.

I have a link on my page:

`<a href="http://server/svn/REPO/branches/MyBranch/Somefile.cs"`>Somefile.cs</a>`

In the extenstion options, I have correct path to TortoiseProc.exe set. 
In my repository list I have added:

- http://server/svn/REPO/branches/MyBranch/
- http://server/svn/

But when I open my html file the links appear normal. Clicking on the link just takes me to the raw file in on server. 

What am I doing wrong?

**Comment by masamitsu-murase** [comment]
It seems that your procedure is correct.

Could you let me know the followings to isolate your issue?
* What occurs when you right-click the link to "http://.../Somefile.cs" and select "Open Repo-browser" in the context menu?

**Comment by sheam** [comment]
It correctly opens the repo browser. It it also opens blame correctly, etc.

In options I have the hover option checked, and no hover info is showing over links.

I tried adding data-tsvn-info="tsvn[log][12,8]" to the link, but they seem to be ignored. It seems it is simply ignoring my `<a>` tags.

**Comment by masamitsu-murase** [comment]
Thank you for the confirmation.

Could you kindly check the followings for the further isolation?
* If your HTML file is a local file, could you verify "Allow access to file URLs" is turned on in "Details" setting for "Open TortoiseSVN for Google Chrome" in "chrome://extensions"?
* If you are in incognito mode, could you verify "Allow in incognito" is turned on?
* Otherwise, could you add "https://svn.ruby-lang.org/repos/ruby/trunk" to "URL list of Subversion repositories" in the extension options page?
  Then, could you check what occurs when you click "trunk/" link in the page, "https://svn.ruby-lang.org/repos/ruby/"?

To be honest, I haven't replicated the issue yet.

Regards,
Murase

**Comment by sheam** [comment]
The allow access to 'file URL's fixed it. This makes sense because I am just viewing an HTML file that a batch process generated.

Thanks so much!
